server:
  port: 9002
  servlet:
    context-path: /admin/api
  tomcat:
    uri-encoding: UTF-8
    accept-count: 200
    max-threads: 300
spring:
  redis:
    database: 5
    port: 6380
    host: database
    password: "ENC(P0n5xRQYwNlAVS64Tdm06aJ0fEX6SPjw)"
  application:
    name: chaser-admin-api
  datasource:
    url: jdbc:mysql://database:3307/chaser_admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: chaser_admin
    password: "ENC(igdNt88NTF8N2Pol4j33erm67yigN2fB)"
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:logging-dev.xml
  level:
    top.chaser.framework.boot: debug
    root: info
    top.chaser.admin.api.mapper: trace
    top.chaser.admin.api: debug
    top.chaser.framework.starter.uaa.resource.service.impl.PermissionServiceImpl: debug
  logback:
    rollingpolicy:
      max-file-size: 100MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#  base-packages: com.cdcconline.rop
  mapper-locations: "classpath*:mapper/*.xml"
pagehelper:
  #  helperDialect：分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。配置时，可以使用下面的缩写值：
  #  oracle,mysql,mariadb,sqlite,hsqldb,postgresql,db2,sqlserver,informix,h2,sqlserver2012,derby
  #  特别注意：使用 SqlServer2012 数据库时，需要手动指定为 sqlserver2012，否则会使用 SqlServer2005 的方式进行分页。
  #  你也可以实现 AbstractHelperDialect，然后配置该属性为实现类的全限定名称即可使用自定义的实现方法。
  #  offsetAsPageNum：默认值为 false，该参数对使用 RowBounds 作为分页参数时有效。 当该参数设置为 true 时，会将 RowBounds 中的 offset 参数当成 pageNum 使用，可以用页码和页面大小两个参数进行分页。
  #  rowBoundsWithCount：默认值为false，该参数对使用 RowBounds 作为分页参数时有效。 当该参数设置为true时，使用 RowBounds 分页会进行 count 查询。
  #  pageSizeZero：默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）。
  #  reasonable：分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  #  params：为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
  #  supportMethodsArguments：支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。 使用方法可以参考测试代码中的 com.github.pagehelper.test.basic 包下的 ArgumentsMapTest 和 ArgumentsObjTest。
  #  autoRuntimeDialect：默认值为 false。设置为 true 时，允许在运行时根据多数据源自动识别对应方言的分页 （不支持自动选择sqlserver2012，只能使用sqlserver），用法和注意事项参考下面的场景五。
  #  closeConn：默认值为 true。当使用运行时动态数据源或没有设置 helperDialect 属性自动获取数据库类型时，会自动获取一个数据库连接， 通过该属性来设置是否关闭获取的这个连接，默认true关闭，设置为 false 后，不会关闭获取的连接，这个参数的设置要根据自己选择的数据源来决定。
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: 1qaz2wsx
chaser:
  swagger:
    enable: true
  security:
    jwt:
      private-key: "MIIG/AIBADANBgkqhkiG9w0BAQEFAASCBuYwggbiAgEAAoIBgQCJV6rhbM6FaAWhJqz0cxa6m8obtTA29662luSMThy+9YmY9AMLQJW1uI1fhavWudPiV316LRwc7wvfvO561Wh0dDwgHVYI7+h+HezDtUhrXgUt+GZRMsMB0w5PNQxmVZLngJWxVlqLbGtwcD+3/iRVbLMWo+djKvVNC2uDhYsKDA92buwijLAeHchiKYK3ap1Pz1uvXo/j8NOOuadD+JVlaeKDyz31MdmpP+kNZ5s25ReA3r95WUNgTn70u7EVCbNBLjj8RI7lW/CIa/CoKVaVMqJ+VTsDzI0frVp195WWmYx/wDreHrIIyA49OHzSi4IcWrN50n4pYZ9n9JIYIfs3o312+Vj9fLnGYpyS8n63z7lq+1H8qUQXbOMDOhQQAYTD+uHuzoeYn6SI9gQLsmi0VqGKQZYxwwUGhUKrcwBsQMArsjEgKq7QEp12pb9+zdNvNVX2r7n0aa54TNMcJ/EBoNlEgnxbaLV0mNACEg7qwJCV50bKvw6ewy38ifdhp30CAwEAAQKCAYAdGRrWKdRThWdz7hrEq8GMBce7ORce/jjg7HU9mKsUdjcR1djzQFq3poMlUs/GbZaLpNer0/TZ2HeejovEMISx75Jxh2Wb/SA34CUyjazrOn9EbxVWbLfOIiYs9+NJpyW5sI+Gg/IpCe51YwLM+6Y9BwumZ1F1vDs+eIXt1pRPq6B3CiczZrVFnC/BRGQycf8kUp1tOU6pD3PzEDh0+SzF0LoyDBRzZ31jE2xP77x90+m33vmYPyY8OEVDmqR4/ZXPUZA+Qo8jDg7CxajdnI1AqusCRUYIAxsZwawHmNGj1jwhW+BDR3hvDqQrTGjWGJ2NqXl8wJ4yIa3WXrd68JZHNwObG6uWZM6YKCWPigTtWhHqPbLXU5qMGQWWbCUSIfXCUxfpssotkGNLtl5qQM7+WVkbESgS7jXzUKsFRASOCgWlVFy6uEbmNTUX/OwbSaEgPex/Sk56Rq9tagcVZmcZEDvMdbtdoIlmjYrUpStuJHVD187SCShiVQN53bODYa0CgcEA98EXLA8AhEmtntzGq1/fhZCutwalIisZYvq04lvHx3qyF4aZfSbXzpjvimrpqLvpxydQeKyNt24MjHhZtF3d/OMzG2Sv6RyUUF/1LwnDwEpU5yGuvOWquADQN4WchWewOzpDtr1qO2jAIPJ1UklVn4rStdYMQ3heIbhV8wShRdqsPAEsyV6+kGkdSSeD8fJCcMO2VLLYQfMPf8mVUO2E4J3+Mlpjmb4PH5od4VL7Y9GC+SgP0DhnL90OPN1Y/W5HAoHBAI3p2WCAiGTrzgrUn5yORA9Q6JC1lp0UKoHZwYW6bHeaA5W1oJVHgZvJ/Od8W07OVFAhR1g039HFjhmEHTg8FK2laZHRV8CI1l3AeDvaVzvBzmmQ3VzQFVmHvCa78X+FBEND9cMy/G3HbHiAvlYC9wkQVJonX7637mIksqUEHyKXDYOAhrAyxQEtNdEo1HbUhAjzvUtRfnnbt6gB82kUBus0lVQrmlz28TQkFE1mtKAQ0pIpo+iDZr8hT5OyycXKGwKBwFQd9+sakNdZWJxmYwGOhIqJq/gyRmDKd00Wx9FOzg6ZRtwb9AL87CqV3EaHtBt46Y+XdofyNg+ASrxqpDJL6HHTBegYEG26KVT8r3cv/olL83WiBvzVkVf11rvzHkhhAwGo75KczvOqxgipqVGt2mdXr+DS8sj5liQmvO/Ms6DO9MlOsNER3OuU9L+Arhi4Yvx8RmyNaEVD7BA79flLG2FT4xlffQ+W6vWU0u5MyVODr88+XdgZPleO2yWpFWy+QwKBwAZYOCG6XV61tCaDzwb+zUgqA9vEYpFvP19CzwYdiY/nUNW2oxFJex/t7eKjiqmBS/+xHTFyW7dTL8EwSOYkuX/x70BXraar93mFi1qRrmi7h3DsyxjFLM8t5FmO+YML/V7MgQZTFzoJOm5Aw0GxLD45fq7Np9gs/PliTqJWBtZTDoWcj2j9PBWLYeaR/r25TpXf38yoPhFQo2tdevZtsMl/NlXnBSW23J3KJyY2u0iUt/VU60EP7t4IrTgbPC4dlQKBwDE3/WyDALFkUGNGFOC+iuszlQfPNqFKKEYWMAvVRPOOaN8AI50fe8siGh2YKt8eQ8SANJ+ShsC5zpUt15bDPHod7Oq3dqEvQ+mImMv8Io08DwxqQOgmPhFBeT2uZZE/2CMlNY85oLckk5zGA33t8+EYF+bYM6KMIELt3vem6QG8md/CKHZuQ4GSr4MyXY+8zwWv6q/FjzDuSmdV7Rj2EJjNS4YEXYdBi9EjNnFgXyZTi5AhXZum755k1k/O60OWYw=="
      public-key: "MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAiVeq4WzOhWgFoSas9HMWupvKG7UwNveutpbkjE4cvvWJmPQDC0CVtbiNX4Wr1rnT4ld9ei0cHO8L37zuetVodHQ8IB1WCO/ofh3sw7VIa14FLfhmUTLDAdMOTzUMZlWS54CVsVZai2xrcHA/t/4kVWyzFqPnYyr1TQtrg4WLCgwPdm7sIoywHh3IYimCt2qdT89br16P4/DTjrmnQ/iVZWnig8s99THZqT/pDWebNuUXgN6/eVlDYE5+9LuxFQmzQS44/ESO5VvwiGvwqClWlTKiflU7A8yNH61adfeVlpmMf8A63h6yCMgOPTh80ouCHFqzedJ+KWGfZ/SSGCH7N6N9dvlY/Xy5xmKckvJ+t8+5avtR/KlEF2zjAzoUEAGEw/rh7s6HmJ+kiPYEC7JotFahikGWMcMFBoVCq3MAbEDAK7IxICqu0BKddqW/fs3TbzVV9q+59GmueEzTHCfxAaDZRIJ8W2i1dJjQAhIO6sCQledGyr8OnsMt/In3Yad9AgMBAAE="
    resource-server:
      white-list-pattern:
        - /uaa/user
